### ISSUE TITLE
Linux环境报错

### ISSUE THREAD

**Issue by fanslead** [zmjack/Chinese#1]
linux环境调用报错
`System.TypeInitializationException: The type initializer for 'Chinese.ChineseNumber' threw an exception.\n ---> System.TypeInitializationException: The type initializer for 'Microsoft.International.Converters.TraditionalChineseToSimplifiedConverter.OfficeConversionEngine' threw an exception.\n ---> System.TypeInitializationException: The type initializer for 'Microsoft.Win32.Registry' threw an exception.\n ---> System.PlatformNotSupportedException: Registry is not supported on this platform.\n   at Microsoft.Win32.RegistryKey.OpenBaseKeyCore(RegistryHive hKey, RegistryView view)\n   at Microsoft.Win32.Registry..cctor()\n   --- End of inner exception stack trace ---\n   at Microsoft.International.Converters.TraditionalChineseToSimplifiedConverter.OfficeConversionEngine..cctor()\n   --- End of inner exception stack trace ---\n   at Microsoft.International.Converters.TraditionalChineseToSimplifiedConverter.OfficeConversionEngine.Create()\n   at Microsoft.International.Converters.TraditionalChineseToSimplifiedConverter.ChineseConverter.Convert(String text, ChineseConversionDirection direction)\n   at Chinese.ChineseConverter.ToTraditional(String chinese)\n   at Chinese.ChineseNumber.<>c.<set_SuperiorLevels>b__9_0(String word)\n   at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()\n   at System.Collections.Generic.EnumerableHelpers.IterativeCopy[T](IEnumerable`1 source, T[] array, Int32 arrayIndex, Int32 count)\n   at System.Collections.Generic.EnumerableHelpers.Copy[T](IEnumerable`1 source, T[] array, Int32 arrayIndex, Int32 count)\n   at System.Linq.Enumerable.Concat2Iterator`1.ToArray()\n   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)\n   at Chinese.ChineseNumber.set_SuperiorLevels(String[] value)\n   at Chinese.ChineseNumber..cctor()\n   --- End of inner exception stack trace ---\n   at Chinese.ChineseCurrency.GetString(Decimal money, ChineseNumberOptions options)\n   at Infrastructure.GeneralAnalytical.TransformCharOrNumber.SumConvert(String text, Decimal number, ConvertType Type, Different different) in`

**Comment by zmjack** [comment]
感谢反馈，这个问题已经得到修复。
在未来版本中，本库将不再依赖 Microsoft.International.* 相关类库。

请通过 NuGet 安装 v0.3.5+ 版本使用。

**Comment by fanslead** [comment]
谢谢，更新后可用
