### ISSUE TITLE
多音字是怎么选的？

### ISSUE THREAD

**Issue by bytesource** [zmjack/Chinese#4]
Jack，你好！

我想问一下多音字的拼音是怎么选的？

比如，我用F#做了这个测试：

```` fsharp
let autoTextSentence = "这只鸟跑得很快。"

let autoConversionTest = 
    Pinyin.GetString(autoTextSentence, PinyinFormat.Default)
// val it : string = "zhe4 zhi1 diao3 pao2 de2 hen3 kuai4。"
````

如果按照多音字的使用频率来选，”鸟“的拼音应该是niao3，而”跑“的拼音应该是pao3。

`Chinese` 有没有一个设置可以让它按照多音字的使用频率来选拼音吗？

**Comment by zmjack** [comment]
感谢反馈。试试新版吧（v0.4.1+）。

之前版本是按照发音排序后取的第一个值，确实会出现更多的问题。

新版本为每个单字设置了默认值作为常用发音，这样在没有词库支持下会准确一些。

以下是我的测试：

![image](https://user-images.githubusercontent.com/24598247/119056349-21ced680-b9fd-11eb-8961-20db6e4db825.png)

**Comment by bytesource** [comment]
太好了！我以为我用的是最新版本。谢谢你提醒我要更新版本！
